// Replace the content in <>
// Identify your target audience and explain how/why they would use this Quick Start.
//Avoid borrowing text from third-party websites (copying text from AWS service documentation is fine). Also, avoid marketing-speak, focusing instead on the technical aspect.

This Quick Start deploys Track-It! on the Amazon Web Services (AWS) Cloud. Track-It! offers features to conduct your IT help desk services, including problem ticketing, change management, purchasing, and inventory. With BMC Client Management, Track-It! also helps with IT endpoint management, providing a central point of patch deployment to all devices on your network. For more information, see the https://www.trackit.com/help-desk-software/[Track-It! website]. This deployment uses AWS Managed Microsoft Active Directory (AD) to integrate your existing on-premises AD.

== Before you begin
Things you will need for setup: 

. *An Amazon Web Services account* – You will need this in order to set up, run and pay for the servers and resources on AWS that you will be using to host your {partner-product-short-name} server.  

. *Software licenses for {partner-product-short-name}* – You can purchase these from BMC Software in advance OR any time within the 90-day trial period that comes with this server instance. 

. *Choose between a 'registered domain name with associated SSL certificate' or a 'random domain name and self-signed certificate'* - If you have an existing registered domain name or wish to register a new domain name, you may set this up using Amazon Route 53 service. 
+
[NOTE]
=====
If you have an existing domain name registered with another registrar then you
have the option of transferring it over to Route 53. Consult the AWS documentation
located https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html[here^] for guidance.


If you have an existing certificate issued for your domain, it is possible to import it
in AWS Certificate Manager (ACM). Consult the AWS documentation located https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html[here^] for guidance.


[start=4]
. *What server size you need* – This is an option during the installation and the different sizes have different memory, disk space, and CPU settings, which could cost you more or less depending on which you select. Most users will be fine with the _Small_ server setup but this is something you should consider and be prepared to answer. 
+
Details on the available sizing options are available in the link:#_sizing[Sizing] section of this guide and the https://docs.bmc.com/docs/trackit2020/en/sizing-and-scalability-considerations-912125648.html[Sizing and scalability considerations^] page of the {partner-product-short-name} online documentation.

. *IP Addresses to Whitelist* – You may need this if you wish to restrict which users/computers can connect to your {partner-product-short-name} server.  There is a configuration option during the setup which allows you to enter a CIDR (pronounced _Cider_) or range of IP addresses that are allowed to connect to your {partner-product-short-name} server.  If you aren’t sure or don’t know, you can always use the default setting there and change it later.  