// Replace the content in <>
// Describe or link to specific knowledge requirements; for example: “familiarity with basic concepts in the areas of networking, database operations, and data encryption” or “familiarity with <software>.”

This Quick Start assumes familiarity with various functions or components of a typical Help Desk software like Asset Management, Change Management, Purchasing, etc. and setting up or configuring Microsoft Active Directory Services and on-premises Exchange or Office365 accounts. This would also need understanding of Amazon Route 53 for setting up correct DNS entries for the Amazon EC2 instance.

==== Using a registered domain
The {partner-product-short-name} Quick Start uses a domain name for its HTTPS based end-points. You may choose to use a domain name registered with Amazon Route 53 along with an associated SSL certificate issued by a trusted certificate authority (CA). Although, this is an optional step it is recommended for a more secure experience for your users.

If you choose not to use an Amazon Route 53 registered domain name, a random domain name will be generated. However, the certificate associated with this domain name is a self-signed certificate. The default behavior in web browsers is to not trust such certificates. As a result your users will see a browser warning whenever any web end-point is accessed.

==== Microsoft Active Directory
The {partner-product-short-name} Quick Start deploys a Microsoft Active Directory domain using AWS Directory Service for Microsoft Active Directory, also known as AWS Managed Microsoft Active Directory (AD). The DNS and NetBIOS names of the domain can be customized using parameters in the template.
Depending on your requirements you can choose either Standard or Enterprise edition. For more details on these options consult the AWS documentation located https://docs.aws.amazon.com/directoryservice/latest/admin-guide/what_is.html[here^].

The {partner-product-short-name} EC2 instance is domain-joined to this AD domain.

===== Windows integrated authentication
{partner-product-short-name} supports authenticating users with Windows integrated authentication. This is an optional feature.

In order to have users on your on-premises AD instance authenticate in {partner-product-short-name} successfully, a two-way trust relationship needs to be established between your on-premises AD and the AWS Managed Microsoft AD. For more details on how to enable this consult the AWS documentation located https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_connect_existing_infrastructure.html[here^].

==== Sizing
The {partner-product-short-name} Quick Start deploys an Amazon EC2 instance. You can customize the size of this instance depending on your needs. The following table lists the sizes and the instance type.

For more details on sizing and recommendations consult the {partner-product-short-name} documentation on https://docs.bmc.com/docs/display/trackit2020/Sizing+and+scalability+considerations[Sizing and scalability considerations^].

For more details about Amazon EC2 instance types see https://aws.amazon.com/ec2/instance-types/[Amazon EC2 Instance Types^].

|===
|Size |Amazon EC2 instance type |Volume size (in GB)

// Space needed to maintain table headers
|Small

Up to 5 active technicians and up to 100 active requestors |m5.xlarge |100
|Medium

Up to 15 active technicians and up to 200 active requestors |m5.2xlarge |150
|Large

More than 15 active technicians and more than 200 active requestors |m5.2xlarge |300
|===